default:
  extensions:
    Behat\MinkExtension\Extension:
      base_url: http://test.pizza-store.loc/
      goutte: ~
      selenium2: ~
  paths:
    features: ../features
    bootstrap: ../features/bootstrap